import { Unbounded } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AuthContextProvider from "./context/AuthContext";

const unbounded = Unbounded({ subsets: ["latin"] });

export const metadata = {
  title: "SparkFilter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={unbounded.className}>
        <AuthContextProvider>
        <Navbar></Navbar>
          {children}
        <Footer></Footer>
        </AuthContextProvider>

      </body>
    </html>
  );
}
